/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author thinh
 */
import java.awt.Desktop;
import java.awt.Frame;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import response.HDCTResponse;
import response.HoaDonResponse;
import response.XemCTHDResponse;
import service.HoaDonService;
import util.ExportPDFHoaDon;

public class HoaDonForm extends javax.swing.JPanel {

    /**
     * Creates new form HoaDonForm
     */
    DefaultTableModel model;
    DefaultTableModel model2;
    ArrayList<HoaDonResponse> list = new ArrayList<>();
    ArrayList<HDCTResponse> listCT = new ArrayList<>();
    ArrayList<XemCTHDResponse> listxemCT = new ArrayList<>();
    HoaDonService service = new HoaDonService();
    private Integer trangthai = null;
    private Date ngayBD = null;
    private Date ngayKT = null;
    private Integer HTthanhtoan = null;
    private Integer totalPage = null;
    private Integer size = 10;
    private Integer page = null;
    private String maHoaDonSelected = null; // để lấy ra mã hóa đơn khi click  

    public HoaDonForm() {
        initComponents();

        model = (DefaultTableModel) TbHoaDon.getModel();
        model2 = (DefaultTableModel) HDCTtable.getModel();
        page = 1;
        totalPage = (int) Math.ceil((double) service.getAll().size() / size);
        tongTrangLb.setText(totalPage + "");
        trangLb.setText(page + "");
        trangthai = null;
        HTthanhtoan = null;
        ngayBD = null;
        ngayKT = null;
        try {
            list = service.loc("", 0, null, null, null, null);
            showData(list);
        } catch (Exception e) {
        }
    }

    private void showData(ArrayList<HoaDonResponse> listHDS) {
        model.setRowCount(0);
        for (HoaDonResponse hds : listHDS) {
            Object data[] = {
                hds.getMaHD(),
                hds.getNgayTao(),
                hds.getNgayThanhToan(),
                hds.getThanhTien(),
                hds.getGiamGiaKM(),
                (hds.getHinhThucThanhToan() == 0 ? "Tiền mặt"
                : (hds.getHinhThucThanhToan() == 1 ? "Chuyển khoản" : "Kết hợp")),
                hds.getMaNV(),
                hds.getTenKH(),
                (hds.getTrangThai() == 1 ? "Đã thanh toán" : "Chưa thanh toán")};
            model.addRow(data);
        }
    }

    private void showHDCT(ArrayList<HDCTResponse> listHDCT) {
        model2.setRowCount(0);
        for (HDCTResponse hdct : listHDCT) {
            Object data[] = {
                hdct.getMaSP(),
                hdct.getTenSP(),
                hdct.getHang(),
                hdct.getMau(),
                hdct.getSize(),
                hdct.getSoLuong(),
                hdct.getDonGia(),
                hdct.getTongTien()
            };
            model2.addRow(data);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        timTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        trangThaiCbo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        thanhToanCbo = new javax.swing.JComboBox<>();
        locBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbHoaDon = new javax.swing.JTable();
        prevBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        tongTrangLb = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        trangLb = new javax.swing.JLabel();
        startDateDC = new com.toedter.calendar.JDateChooser();
        endDateDC = new com.toedter.calendar.JDateChooser();
        chitietBtn = new javax.swing.JButton();
        inBtn = new javax.swing.JButton();
        xuatFileBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        HDCTtable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel1.setText("Tìm kiếm hóa đơn:");

        jLabel4.setText("Trạng thái hóa đơn:");

        trangThaiCbo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Chờ thanh toán", "Đã thanh toán" }));
        trangThaiCbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trangThaiCboActionPerformed(evt);
            }
        });

        jLabel5.setText("Hình thức thanh toán:");

        thanhToanCbo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Tiền mặt", "Chuyển khoản", "Kết hợp" }));
        thanhToanCbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thanhToanCboActionPerformed(evt);
            }
        });

        locBtn.setBackground(new java.awt.Color(0, 102, 255));
        locBtn.setForeground(new java.awt.Color(255, 255, 255));
        locBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/timkiem.png"))); // NOI18N
        locBtn.setText("Tìm kiếm");
        locBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locBtnActionPerformed(evt);
            }
        });

        TbHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Ngày tạo", "Ngày thanh toán", "Tổng tiền", "Tiền giảm giá", "Hình thức thanh toán", "Mã NV", "Tên KH", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbHoaDon);
        if (TbHoaDon.getColumnModel().getColumnCount() > 0) {
            TbHoaDon.getColumnModel().getColumn(5).setResizable(false);
        }

        prevBtn.setBackground(new java.awt.Color(0, 102, 255));
        prevBtn.setForeground(new java.awt.Color(255, 255, 255));
        prevBtn.setText("Prev");
        prevBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevBtnActionPerformed(evt);
            }
        });

        nextBtn.setBackground(new java.awt.Color(0, 102, 255));
        nextBtn.setForeground(new java.awt.Color(255, 255, 255));
        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        tongTrangLb.setText("jLabel6");

        jLabel7.setText("/");

        trangLb.setText("jLabel8");

        chitietBtn.setBackground(new java.awt.Color(0, 102, 255));
        chitietBtn.setForeground(new java.awt.Color(255, 255, 255));
        chitietBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgmain/hoadon.png"))); // NOI18N
        chitietBtn.setText("Xem chi tiết");
        chitietBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chitietBtnActionPerformed(evt);
            }
        });

        inBtn.setBackground(new java.awt.Color(0, 102, 255));
        inBtn.setForeground(new java.awt.Color(255, 255, 255));
        inBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgmain/hoadon.png"))); // NOI18N
        inBtn.setText("In hoá đơn");
        inBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inBtnActionPerformed(evt);
            }
        });

        xuatFileBtn.setBackground(new java.awt.Color(0, 102, 255));
        xuatFileBtn.setForeground(new java.awt.Color(255, 255, 255));
        xuatFileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/them.png"))); // NOI18N
        xuatFileBtn.setText("Xuất file Excel");
        xuatFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xuatFileBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Từ:");

        jLabel3.setText("Đến:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(prevBtn)
                        .addGap(40, 40, 40)
                        .addComponent(trangLb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tongTrangLb)
                        .addGap(42, 42, 42)
                        .addComponent(nextBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(locBtn)))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(trangThaiCbo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(chitietBtn))
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(thanhToanCbo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(inBtn)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(xuatFileBtn))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(timTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(19, 19, 19)
                                        .addComponent(startDateDC, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(endDateDC, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(timTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(startDateDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(trangThaiCbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(thanhToanCbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(endDateDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locBtn)
                    .addComponent(chitietBtn)
                    .addComponent(inBtn)
                    .addComponent(xuatFileBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prevBtn)
                    .addComponent(nextBtn)
                    .addComponent(tongTrangLb)
                    .addComponent(jLabel7)
                    .addComponent(trangLb))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {chitietBtn, inBtn, locBtn, xuatFileBtn});

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Hóa đơn chi tiết"));

        HDCTtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Hãng", "Màu", "Size", "Số lượng", "Đơn giá", "Tổng tiền"
            }
        ));
        jScrollPane2.setViewportView(HDCTtable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void locBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locBtnActionPerformed
        String tim = timTxt.getText();
        if (startDateDC.getCalendar() != null) {
            ngayBD = startDateDC.getCalendar().getTime();
        }
        if (endDateDC.getCalendar() != null) {
            ngayKT = endDateDC.getCalendar().getTime();
        }
        if (ngayBD != null && ngayKT != null && ngayBD.getTime() > ngayKT.getTime()) {
            JOptionPane.showMessageDialog(this, "Ngày bắt đầu phải trước ngày kết thúc");
            return;//
        }
        page = 1;
        list = service.loc(tim, page - 1, trangthai, HTthanhtoan, ngayBD, ngayKT);
        showData(list);
        trangLb.setText(page + "");
        ArrayList<HoaDonResponse> listHDAll = service.countSearch(tim, trangthai, HTthanhtoan, ngayBD, ngayKT);
        totalPage = (int) Math.ceil((double) listHDAll.size() / size);
        tongTrangLb.setText(totalPage + "");
    }//GEN-LAST:event_locBtnActionPerformed

    private void TbHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbHoaDonMouseClicked
        int row = TbHoaDon.getSelectedRow();
        HoaDonResponse hd = list.get(row);
        showHDCT(service.getAllHDCT(hd.getMaHD()));
        maHoaDonSelected = hd.getMaHD();
    }//GEN-LAST:event_TbHoaDonMouseClicked

    private void prevBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevBtnActionPerformed
        if (page == 1) {
            return;
        }
        page = page - 1;
        trangLb.setText(page + "");
        list = service.loc(timTxt.getText(), page - 1, trangthai, HTthanhtoan, ngayBD, ngayKT);
        showData(list);
    }//GEN-LAST:event_prevBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        if (page >= totalPage) {
            return;
        }
        page = page + 1;
        //System.out.println(page);
        trangLb.setText(page + "");
        list = service.loc(timTxt.getText(), page - 1, trangthai, HTthanhtoan, ngayBD, ngayKT);
        showData(list);
    }//GEN-LAST:event_nextBtnActionPerformed

    private void trangThaiCboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trangThaiCboActionPerformed
        String loctt = (String) trangThaiCbo.getSelectedItem();
        if (loctt.equals("Tất cả")) {
            trangthai = null;
        }
        if (loctt.equals("Đã thanh toán")) {
            trangthai = 1;
        }
        if (loctt.equals("Chờ thanh toán")) {
            trangthai = 0;
        }
        list = service.loc(timTxt.getText(), 0, trangthai, HTthanhtoan, ngayBD, ngayKT);
        showData(list);
        totalPage = (int) Math.ceil((double) service.countSearch(timTxt.getText(), trangthai, HTthanhtoan, ngayBD, ngayKT).size() / size);
        tongTrangLb.setText(totalPage + "");
    }//GEN-LAST:event_trangThaiCboActionPerformed

    private void thanhToanCboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thanhToanCboActionPerformed
        String locthanhToan = (String) thanhToanCbo.getSelectedItem();
        if (locthanhToan.equals("Tất cả")) {
            HTthanhtoan = null;
        }
        if (locthanhToan.equals("Chuyển khoản")) {
            HTthanhtoan = 1;
        }
        if (locthanhToan.equals("Tiền mặt")) {
            HTthanhtoan = 0;
        }
        if (locthanhToan.equals("Kết hợp")) {
            HTthanhtoan = 2;
        }
        list = service.loc(timTxt.getText(), 0, trangthai, HTthanhtoan, ngayBD, ngayKT);
        showData(list);
        totalPage = (int) Math.ceil((double) service.countSearch(timTxt.getText(), trangthai, HTthanhtoan, ngayBD, ngayKT).size() / size);
        tongTrangLb.setText(totalPage + "");
    }//GEN-LAST:event_thanhToanCboActionPerformed

    private void chitietBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chitietBtnActionPerformed
        int row = TbHoaDon.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Chưa chọn hoá đơn để xem chi tiết");
            return;
        }
        HoaDonResponse hd = list.get(row);
        //showHDCT(service.getAllHDCT(hd.getMaHD()));
        maHoaDonSelected = hd.getMaHD();
        XemCTHDResponse xemCT = service.xemchitiet(maHoaDonSelected);
        JDialogCTHD dialog = new JDialogCTHD((Frame) SwingUtilities.getWindowAncestor(this), true, xemCT);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);

    }//GEN-LAST:event_chitietBtnActionPerformed

    private void xuatFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xuatFileBtnActionPerformed

        try {
            JFileChooser FileChooser = new JFileChooser();
            FileChooser.showSaveDialog(this);
            File saveFile = FileChooser.getSelectedFile();

            if (saveFile != null) {
                saveFile = new File(saveFile.toString());
                Workbook wb = new XSSFWorkbook();
                Sheet sheet = wb.createSheet("DanhSachHoaDon");
                Row rowCol = sheet.createRow(0);
                Cell cell = rowCol.createCell(0);
                cell.setCellValue("Mã hoá đơn");

                cell = rowCol.createCell(1);
                cell.setCellValue("Ngày tạo");

                cell = rowCol.createCell(2);
                cell.setCellValue("Ngày thanh toán");

                cell = rowCol.createCell(3);
                cell.setCellValue("Hình thức thanh toán");

                cell = rowCol.createCell(4);
                cell.setCellValue("Tổng tiền");

                cell = rowCol.createCell(5);
                cell.setCellValue("Tiền khách chuyển khoản");

                cell = rowCol.createCell(6);
                cell.setCellValue("Tiền khách trả");

                cell = rowCol.createCell(7);
                cell.setCellValue("Tiền thừa");

                cell = rowCol.createCell(8);
                cell.setCellValue("Mã nhân viên");

                cell = rowCol.createCell(9);
                cell.setCellValue("Tên nhân viên");

                cell = rowCol.createCell(10);
                cell.setCellValue("Tên khách hàng");

                cell = rowCol.createCell(11);
                cell.setCellValue("Địa chỉ");

                cell = rowCol.createCell(12);
                cell.setCellValue("SĐT (Khách hàng)");

                cell = rowCol.createCell(13);
                cell.setCellValue("Tiền giảm giá");

                cell = rowCol.createCell(14);
                cell.setCellValue("Trạng thái");

                int rowNum = 1; // Bắt đầu từ dòng 1 vì dòng 0 là tiêu đề
                listxemCT = service.xuatDSHD();
                SimpleDateFormat setDate = new SimpleDateFormat("dd/MM/yyyy hh:mm aa");

                for (XemCTHDResponse xemhoaDon : listxemCT) {
                    Row row = sheet.createRow(rowNum++);

                    cell = row.createCell(0);
                    cell.setCellValue(xemhoaDon.getMaHD());

                    cell = row.createCell(1);
                    cell.setCellValue(setDate.format(xemhoaDon.getNgayTao()));

                    cell = row.createCell(2);
                    cell.setCellValue(setDate.format(xemhoaDon.getNgayThanhToan()));

                    cell = row.createCell(3);
                    cell.setCellValue((xemhoaDon.getHTthanhtoan() == 0 ? "Tiền mặt"
                            : (xemhoaDon.getHTthanhtoan() == 1 ? "Chuyển khoản" : "Kết hợp")));

                    cell = row.createCell(4);
                    cell.setCellValue(xemhoaDon.getTongTien());

                    cell = row.createCell(5);
                    cell.setCellValue(xemhoaDon.getTienkhachCK());

                    cell = row.createCell(6);
                    cell.setCellValue(xemhoaDon.getTienKhachTra());

                    cell = row.createCell(7);
                    cell.setCellValue(xemhoaDon.getTienThua());

                    cell = row.createCell(8);
                    cell.setCellValue(xemhoaDon.getMaNV());

                    cell = row.createCell(9);
                    cell.setCellValue(xemhoaDon.getTenNV());

                    cell = row.createCell(10);
                    cell.setCellValue(xemhoaDon.getTenKH());

                    cell = row.createCell(11);
                    cell.setCellValue(xemhoaDon.getDiaChi());

                    cell = row.createCell(12);
                    cell.setCellValue(xemhoaDon.getSdt());

                    cell = row.createCell(13);
                    cell.setCellValue(xemhoaDon.getTienGiam());

                    cell = row.createCell(14);
                    cell.setCellValue((xemhoaDon.getTrangThai() == 0 ? "Chưa thanh toán" : "Đã thanh toán"));

                }
                FileOutputStream out = new FileOutputStream(new File(saveFile.toString()));
                wb.write(out);
                wb.close();
                out.close();
                openFile(saveFile.toString());
            } else {
                JOptionPane.showMessageDialog(null, "Đã hủy xuất file");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_xuatFileBtnActionPerformed

    private void inBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inBtnActionPerformed
        int row = TbHoaDon.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(this, "Chưa chọn hoá đơn để in");
            return;
        }
        HoaDonResponse hd = list.get(row);
        maHoaDonSelected = hd.getMaHD();
        if(hd.getTrangThai() == 0){
            JOptionPane.showMessageDialog(this, "Hóa đơn này chưa thanh toán !");
            return;
        }
        XemCTHDResponse xemCT = service.xemchitiet(maHoaDonSelected);
        listCT = service.getAllHDCT(hd.getMaHD());
        maHoaDonSelected = hd.getMaHD();
        JFileChooser avatarChooser = new JFileChooser("D:\\");
        avatarChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); //Giới hạn chỉ chọn đc thư mục
        FileNameExtensionFilter avatarFilter = new FileNameExtensionFilter("Danh sách hoá đơn", "xlsx");
        avatarChooser.setFileFilter(avatarFilter);
        avatarChooser.setAcceptAllFileFilterUsed(false);
        int selectFileCheck = avatarChooser.showOpenDialog(this);
        File selectedFile = avatarChooser.getSelectedFile();
        if (!(selectFileCheck == JFileChooser.APPROVE_OPTION)) {
            return;
        }
        
        String path = selectedFile.getAbsolutePath();

        ExportPDFHoaDon export = new ExportPDFHoaDon();
        export.exportBill(xemCT, listCT, path);

        JOptionPane.showMessageDialog(this, "In hóa đơn thành công");
    }//GEN-LAST:event_inBtnActionPerformed

    public void openFile(String file) {
        try {
            File path = new File(file);
            Desktop.getDesktop().open(path);
        } catch (IOException ioe) {
            System.out.println(ioe);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable HDCTtable;
    private javax.swing.JTable TbHoaDon;
    private javax.swing.JButton chitietBtn;
    private com.toedter.calendar.JDateChooser endDateDC;
    private javax.swing.JButton inBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton locBtn;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton prevBtn;
    private com.toedter.calendar.JDateChooser startDateDC;
    private javax.swing.JComboBox<String> thanhToanCbo;
    private javax.swing.JTextField timTxt;
    private javax.swing.JLabel tongTrangLb;
    private javax.swing.JLabel trangLb;
    private javax.swing.JComboBox<String> trangThaiCbo;
    private javax.swing.JButton xuatFileBtn;
    // End of variables declaration//GEN-END:variables
}
